### ISSUE TITLE
Malformed packet error ('Tins::malformed_packet')

### ISSUE THREAD

**Issue by LeStegii** [insomniacslk/python-dublin-traceroute#21]
# Malformed packet error ('Tins::malformed_packet')
When using dublin traceroute in python, sometimes the program crashes unexpectedly with an `Malformed packet` error as seen below:

```
terminate called after throwing an instance of 'Tins::malformed_packet'
  what():  Malformed packet
```

This makes it impossible to use in large scale programs for me which is annoying as it has the best python bindings for any traceroute alternative I know.

The related python code is the following:

```python
traceroute = dublintraceroute.DublinTraceroute(target, npaths=queries)
result: dict[str, any] = traceroute.traceroute()
```

The error appears right after `172.217.16.202` is traced (but only sometimes).
The main problem is that the error is uncatchable in python. If it was catchable, my issue could easiliby be resolved by retrying.

Related to #10

**Comment by LeStegii** [comment]
Some exceptions are now caught in my fork using (see https://github.com/LeStegii/python-dublin-traceroute/commit/e4ae97cd21ca142f79ecbc30cebd096034acfb19). I'd love to make a PR, but for this I'd rather add all possible exceptions before.

**Comment by insomniacslk** [comment]
hi @LeStegii , thanks for catching this! I will have a few free days within the next couple of weeks and should be able to take a look. My suggestion is to make a PR with the changes from your branch, then we can add more exception handling in separate commits, how does that sound?

**Comment by LeStegii** [comment]
Sounds great! I'll open a draft then
